#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("QCSAndroid.Resource", IsApplication=true)]

namespace QCSAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::QCSAndroid.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::QCSAndroid.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::QCSAndroid.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int agrement_type_array = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int installation_type_array = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int machine_brand_array = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int region_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Finning_16_16 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Finning_long = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000c
			public const int btnSaveAndClose = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int btnSaveAndScan = 2131165195;
			
			// aapt resource value: 0x7f07001e
			public const int btnSaveSettings = 2131165214;
			
			// aapt resource value: 0x7f07000e
			public const int btnScan = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int btnSend = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int btnSettings = 2131165201;
			
			// aapt resource value: 0x7f070020
			public const int contentFrame = 2131165216;
			
			// aapt resource value: 0x7f07001b
			public const int editCustomerAccountNumber = 2131165211;
			
			// aapt resource value: 0x7f070017
			public const int editEmail = 2131165207;
			
			// aapt resource value: 0x7f070013
			public const int editFirstName = 2131165203;
			
			// aapt resource value: 0x7f070015
			public const int editLastName = 2131165205;
			
			// aapt resource value: 0x7f070004
			public const int editMachineBrand = 2131165188;
			
			// aapt resource value: 0x7f07000a
			public const int editMachineHours = 2131165194;
			
			// aapt resource value: 0x7f070006
			public const int editMachineModel = 2131165190;
			
			// aapt resource value: 0x7f070010
			public const int lstView = 2131165200;
			
			// aapt resource value: 0x7f07000d
			public const int relativeLayout1 = 2131165197;
			
			// aapt resource value: 0x7f07001d
			public const int spnAgreementType = 2131165213;
			
			// aapt resource value: 0x7f070001
			public const int spnInstallationType = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int spnMachineBrand = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int spnMachineYear = 2131165192;
			
			// aapt resource value: 0x7f070019
			public const int spnRegion = 2131165209;
			
			// aapt resource value: 0x7f07001f
			public const int toolbar = 2131165215;
			
			// aapt resource value: 0x7f07001c
			public const int txtAgreementType = 2131165212;
			
			// aapt resource value: 0x7f07001a
			public const int txtCustomerAccountNumber = 2131165210;
			
			// aapt resource value: 0x7f070016
			public const int txtEmail = 2131165206;
			
			// aapt resource value: 0x7f070012
			public const int txtFirstName = 2131165202;
			
			// aapt resource value: 0x7f070000
			public const int txtInstallationType = 2131165184;
			
			// aapt resource value: 0x7f070014
			public const int txtLastName = 2131165204;
			
			// aapt resource value: 0x7f070002
			public const int txtMachineBrand = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int txtMachineHours = 2131165193;
			
			// aapt resource value: 0x7f070005
			public const int txtMachineModel = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int txtMachineYear = 2131165191;
			
			// aapt resource value: 0x7f070018
			public const int txtRegion = 2131165208;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddEdit = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Settings = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int toolbar = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int zxingscanneractivitylayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int zxingscannerfragmentlayout = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040012
			public const int btnSaveAndClose = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int btnSaveAndNext = 2130968593;
			
			// aapt resource value: 0x7f040013
			public const int btnSaveSettings = 2130968595;
			
			// aapt resource value: 0x7f040000
			public const int btnStartScan = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int choose_agreement_type = 2130968585;
			
			// aapt resource value: 0x7f04000e
			public const int choose_machine_brand = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int choose_machine_year = 2130968591;
			
			// aapt resource value: 0x7f040007
			public const int choose_region = 2130968583;
			
			// aapt resource value: 0x7f04001d
			public const int csv_accountNumber = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int csv_agreementType = 2130968606;
			
			// aapt resource value: 0x7f04001b
			public const int csv_email_address = 2130968603;
			
			// aapt resource value: 0x7f04001a
			public const int csv_installer = 2130968602;
			
			// aapt resource value: 0x7f04001c
			public const int csv_region = 2130968604;
			
			// aapt resource value: 0x7f040015
			public const int file_data = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int file_data_csv = 2130968598;
			
			// aapt resource value: 0x7f040014
			public const int file_settings = 2130968596;
			
			// aapt resource value: 0x7f040019
			public const int send_email_subj = 2130968601;
			
			// aapt resource value: 0x7f040017
			public const int send_email_to = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int send_email_to_cc = 2130968600;
			
			// aapt resource value: 0x7f040008
			public const int txt_agreement_type = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int txt_customer_account_number = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int txt_email = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int txt_first_name = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int txt_last_name = 2130968579;
			
			// aapt resource value: 0x7f04000d
			public const int txt_machine_brand = 2130968589;
			
			// aapt resource value: 0x7f040010
			public const int txt_machine_hours = 2130968592;
			
			// aapt resource value: 0x7f04000b
			public const int txt_machine_model = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int txt_machine_year = 2130968588;
			
			// aapt resource value: 0x7f040005
			public const int txt_region = 2130968581;
			
			// aapt resource value: 0x7f04000a
			public const int txt_type_installation = 2130968586;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
